name: Wolf Shaper CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: "Install dependencies"
      run: sudo apt install gcc g++ clang libx11-dev libgl1-mesa-dev liblo-dev libjack-dev gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
      
    - name: "Linux (GCC)"
      env: 
        LINUX: true 
        BUILD_DSSI: true 
        CC: gcc 
        CXX: g++
      run: make
      
    - name: "Linux (Clang)"
      env: 
        LINUX: true
        BUILD_DSSI: true 
        CC: clang 
        CXX: clang++
      run: make clean && make
      
    - name: "Windows (MinGW)"
      env: 
        WIN32: true 
        BUILD_DSSI: false
        CC: x86_64-w64-mingw32-gcc 
        AR: x86_64-w64-mingw32-ar 
        CXX: x86_64-w64-mingw32-g++
      run: make clean && make
